<?php

namespace AppBundle\Repository;

/**
 * ControlSaludRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ControlSaludRepository extends \Doctrine\ORM\EntityRepository
{
}
