<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;

/**
 * DemographicDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DemographicDataRepository extends \Doctrine\ORM\EntityRepository{

	 public function getDemographicData($id_demographic_data)
        {
           $qb = $this->createQueryBuilder('demo')
             ->select('demo')
             ->where('demo =:id_demo')->setParameter('id_demo', $id_demographic_data)
             ->getQuery()
             ->getResult(Query::HYDRATE_ARRAY);
           if($qb!=null){
           	return $qb[0];
           }else return 1;
        } 

     public function insertDemographicId($id){
        
     	
     }  




}
