<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository{

	public function activeUsersNumber(){
		$query = $this->createQueryBuilder('user')
    		->select('count(user.id)')
    		->where('user.deleted=0')
    		->getQuery();
	    return $query->setMaxResults(1)->getOneOrNullResult();
	}

	public function getUsers($cantPags,$busqueda,$activo,$pagactual=1,$username){
		$inicio=((int)$pagactual-1)*$cantPags;
		if (($busqueda!='') or ($activo!='')) {
			$query = $this->createQueryBuilder('user')
    		->where("user.active=$activo and user.deleted=0 and user.username!='$username' and (user.username LIKE '%$busqueda%' OR user.name LIKE '%$busqueda%' OR user.surname LIKE '%$busqueda%' OR user.email LIKE '%$busqueda%')")
    		->setFirstResult($inicio)
    		->setMaxResults($cantPags)
    		->getQuery();
		}
		else{
			$query = $this->createQueryBuilder('user')
    		->where("user.deleted=0 and user.username!='$username'")
    		->setFirstResult($inicio)
    		->setMaxResults($cantPags)
    		->getQuery();
		}
		$usuarios=$query->getResult();
		return $usuarios;
	}

}
