<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository{

	public function activeUsersNumber(){
		$query = $this->createQueryBuilder('user')
    		->select('count(user.id)')
    		->where('user.deleted = :deleted')
    		->setParameter('deleted', false)
    		->getQuery();
	    return $query->setMaxResults(1)->getOneOrNullResult();
	}

	public function getUsers($cantPags,$busqueda,$activo,$pagactual=1,$username){
		$inicio=((int)$pagactual-1)*$cantPags;
		
		$query = 
			$this->createQueryBuilder('user')
			->where("user.deleted= :deleted and user.username!= :username")
			->setParameter('deleted', false)
			->setParameter('username', $username);
    		
		if ($activo != ''){
			$query = 
				$query
					->andWhere('user.active= :activo')
    				->setParameter('activo', true);
		}
		
		if ($busqueda != ''){
			$query = 
				$query
					->andWhere('user.username LIKE :busqueda OR user.name LIKE :busqueda OR user.surname LIKE :busqueda OR user.email LIKE :busqueda')	
		    		->setParameter('busqueda', "%$busqueda%");
		}

		return $query->setFirstResult($inicio)
    		->setMaxResults($cantPags)
    		->getQuery()
    		->getResult();
	}

}
