AppBundle\Entity\ControlSalud:
    properties:
        fecha:
          - NotBlank: ~
          - Date: ~
        peso:
          - NotBlank: ~
          - Type: float
          - Range:
              min: 0
        vacunasCompletas:
          - NotBlank: ~
        maduracionAcorde:
          - NotBlank: ~
        exFisicoNormal:
          - NotBlank: ~
        exFisicoObservaciones:
          - NotBlank: ~
        pc:
          - Type: float
          - Range:
              min: 0
        ppc:
          - Type: float
          - Range:
              min: 0
        talla:
          - Type: float
          - Range:
              min: 0
AppBundle\Entity\Pacient:
    properties:
        name:
          - NotBlank: ~
        surname:
          - NotBlank: ~
        dniNumber:
          - NotBlank: ~
          - Type: integer
          - Range:
              min: 0
        birthDate:
          - NotBlank: ~
          - Date: ~
        gender:
          - NotBlank: ~
          - Choice:
                choices:  [M, F]
        address:
          - NotBlank: ~
        phone:
          - Type: integer
          - Range:
              min: 0
AppBundle\Entity\User:
    properties:
        email:
          - NotBlank: ~
          - Email: 
              checkMX: true
        username:
          - NotBlank: ~
        password:
          - NotBlank: ~
        name:
          - NotBlank: ~
        surname:
          - NotBlank: ~
AppBundle\Entity\DemographicData:
    properties:
        heladera:
          - NotBlank: ~
        electricidad:
          - NotBlank: ~
        mascota:
          - NotBlank: ~
        tipoVivienda:
          - NotBlank: ~
        tipoCalefaccion:
          - NotBlank: ~
        tipoAgua:
          - NotBlank: ~